$schema: http://json-schema.org/draft-07/schema#
$id: kvstore/zip_memory
allOf:
- $ref: KvStore
- type: object
  properties:
    driver:
      const: zip_memory
    zip_memory_key_value_store:
      $ref: ContextResource
      description: |-
        Specifies or references a previously defined
        `Context.zip_memory_key_value_store`.
    atomic:
      type: boolean
      default: true
      description: |-
        Support atomic multi-key transactions.  If set to ``false``, the
        transaction behavior matches that of the `kvstore/file` and
        `kvstore/gcs` drivers, which may be useful for testing purposes.
definitions:
  zip_memory_key_value_store:
    $id: Context.zip_memory_key_value_store
    description: |-
      Represents the zip key-value store.  If multiple `kvstore/zip_memory`
      specifications reference the same `Context.zip_memory_key_value_store`, they
      all refer to the same zip file (set of key/value pairs).
    type: object
  url:
    $id: KvStoreUrl/zip_memory
    allOf:
    - $ref: KvStoreUrl
    - type: string
    type: string
    title: |
      :literal:`zip_memory://` KvStore URL scheme
    description: |
      Zip key-value stores may be specified using the custom
      :file:`zip_memory://{path}` URL syntax, and :file:`zip_memory:memory_address:length` syntax.

      .. admonition:: Examples
         :class: example

         .. list-table::
            :header-rows: 1
            :widths: auto

            * - URL representation
              - JSON representation
            * - ``"zip_memory://"``
              - ``{"driver": "zip_memory"}``
            * - ``"zip_memory://path/to/dataset"``
              - ``{"driver": "zip_memory", "path": "path/to/dataset"}``
